using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using Guna.UI2.WinForms;

namespace OpenUI
{
    public partial class UI : Form
    {
        public UI()
        {
            InitializeComponent();
        }


        private IContainer components = null;
        private Guna2BorderlessForm borderlessForm;
        private Guna2ControlBox closeControlBox;
        private Guna2ControlBox maximizeControlBox;
        private Guna2ControlBox minimizeControlBox;
        private TableLayoutPanel rootLayout;
        private TableLayoutPanel headerLayout;
        private FlowLayoutPanel identityLayout;
        private TableLayoutPanel bodyLayout;
        private FlowLayoutPanel menuLayout;
        private FlowLayoutPanel headerActions;
        private TableLayoutPanel logTabsLayout;
        private Guna2HtmlLabel brandLabel;
        private Guna2HtmlLabel modelLabel;
        private Guna2HtmlLabel versionLabel;
        private Guna2HtmlLabel loginLabel;
        private Guna2HtmlLabel menuLabel;
        private Guna2HtmlLabel systemLabel;
        private Guna2Button clearDispButton;
        private Guna2Button clearLoadButton;
        private Guna2Button openLogButton;
        private Guna2Button programLogTab;
        private Guna2Button otherInfoTab;
        private Guna2Panel stationACard;
        private Guna2Panel centerCard;
        private Guna2Panel stationBCard;
        private TableLayoutPanel stationALayout;
        private TableLayoutPanel centerLayout;
        private TableLayoutPanel stationBLayout;
        private Guna2Button stationATitle;
        private Guna2Button stationANote;
        private FlowLayoutPanel stationAStatus;
        private Guna2Button statusA1;
        private Guna2Button statusA2;
        private Guna2Button statusA3;
        private Guna2Button statusA4;
        private Guna2Button statusA5;
        private Guna2Button pdChartButton;
        private Guna2Button lensTrayButton;
        private TableLayoutPanel stationAPreviewLayout;
        private Guna2Panel pdPreview;
        private Guna2DataGridView stationATrayPreview;
        private Guna2Button stationAProcessHeader;
        private Guna2TextBox stationAProcess;
        private Guna2Button centerTitle;
        private Guna2Button laserValue;
        private Guna2Button centerStationBTitle;
        private Guna2Button centerStationBNote;
        private FlowLayoutPanel centerStatus;
        private Guna2Button centerStatus1;
        private Guna2Button centerStatus2;
        private Guna2Button centerStatus3;
        private Guna2Button centerStatus4;
        private TableLayoutPanel visionLayout;
        private TableLayoutPanel centerCameraLayout;
        private TableLayoutPanel topCameraLayout;
        private Guna2Button centerCameraHeader;
        private Guna2Panel centerCamera;
        private Guna2Button trayHeader;
        private TableLayoutPanel trayLayout;
        private Guna2DataGridView trayTop;
        private Guna2DataGridView trayBottom;
        private Guna2Button trayTopLabel;
        private Guna2Button trayBottomLabel;
        private Guna2Button topCameraHeader;
        private Guna2Panel topCamera;
        private Guna2TextBox measureItems;
        private TableLayoutPanel bTrayLayout;
        private Guna2Button bTrayHeader;
        private Guna2DataGridView bTrayTop;
        private Guna2DataGridView bTrayBottom;
        private Guna2Button bTrayTopLabel;
        private Guna2Button bTrayBottomLabel;
        private Guna2Panel processInfoPanel;
        private Guna2HtmlLabel processInfoTitle;
        private Guna2HtmlLabel totalTimeLabel;
        private Guna2HtmlLabel totalTimeValue;
        private Guna2HtmlLabel processInfoRightTitle;
        private Guna2HtmlLabel rightTimeLabel;
        private Guna2HtmlLabel rightTimeValue;
        private Guna2HtmlLabel currentFlowLabel;
        private Guna2HtmlLabel currentFlowValue;
        private Guna2HtmlLabel metricLabel;
        private Guna2CheckBox showMessageCheck;
        private Guna2Button stopFeedAButton;
        private Guna2Button stopFeedBButton;
        private Guna2Button startButton;
        private Guna2Button stopButton;
        private Guna2Button pauseButton;
        private TableLayoutPanel centerBottomLayout;
        private Guna2TextBox calibrationProcess;
        private Guna2TextBox stationBProcess;
        private Guna2HtmlLabel stationBTitle;
        private Guna2HtmlLabel stationBNote;
        private FlowLayoutPanel stationBStatus;
        private Guna2Button statusB1;
        private Guna2Button statusB2;
        private Guna2Button statusB3;
        private Guna2Button statusB4;
        private Guna2Button statusB5;
        private Guna2TextBox programLog;
        private TableLayoutPanel loadCellLayout;
        private Guna2Button loadCell1;
        private Guna2Button loadCell2;
        private Guna2Button loadCell3;
        private Guna2Button loadCell4;
        private Guna2Button emergencyStop;
        private Guna2HtmlLabel footerLabel;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            this.borderlessForm = new Guna2BorderlessForm(this.components);
            this.closeControlBox = new Guna2ControlBox();
            this.maximizeControlBox = new Guna2ControlBox();
            this.minimizeControlBox = new Guna2ControlBox();
            this.rootLayout = new TableLayoutPanel();
            this.headerLayout = new TableLayoutPanel();
            this.identityLayout = new FlowLayoutPanel();
            this.bodyLayout = new TableLayoutPanel();
            this.menuLayout = new FlowLayoutPanel();
            this.headerActions = new FlowLayoutPanel();
            this.logTabsLayout = new TableLayoutPanel();
            this.brandLabel = new Guna2HtmlLabel();
            this.modelLabel = new Guna2HtmlLabel();
            this.versionLabel = new Guna2HtmlLabel();
            this.loginLabel = new Guna2HtmlLabel();
            this.menuLabel = new Guna2HtmlLabel();
            this.systemLabel = new Guna2HtmlLabel();
            this.clearDispButton = new Guna2Button();
            this.clearLoadButton = new Guna2Button();
            this.openLogButton = new Guna2Button();
            this.programLogTab = new Guna2Button();
            this.otherInfoTab = new Guna2Button();
            this.stationACard = new Guna2Panel();
            this.centerCard = new Guna2Panel();
            this.stationBCard = new Guna2Panel();
            this.stationALayout = new TableLayoutPanel();
            this.centerLayout = new TableLayoutPanel();
            this.stationBLayout = new TableLayoutPanel();
            this.stationATitle = new Guna2Button();
            this.stationANote = new Guna2Button();
            this.stationAStatus = new FlowLayoutPanel();
            this.statusA1 = new Guna2Button();
            this.statusA2 = new Guna2Button();
            this.statusA3 = new Guna2Button();
            this.statusA4 = new Guna2Button();
            this.statusA5 = new Guna2Button();
            this.pdChartButton = new Guna2Button();
            this.lensTrayButton = new Guna2Button();
            this.stationAPreviewLayout = new TableLayoutPanel();
            this.pdPreview = new Guna2Panel();
            this.stationATrayPreview = new Guna2DataGridView();
            this.stationAProcessHeader = new Guna2Button();
            this.stationAProcess = new Guna2TextBox();
            this.centerTitle = new Guna2Button();
            this.laserValue = new Guna2Button();
            this.centerStationBTitle = new Guna2Button();
            this.centerStationBNote = new Guna2Button();
            this.centerStatus = new FlowLayoutPanel();
            this.centerStatus1 = new Guna2Button();
            this.centerStatus2 = new Guna2Button();
            this.centerStatus3 = new Guna2Button();
            this.centerStatus4 = new Guna2Button();
            this.visionLayout = new TableLayoutPanel();
            this.centerCameraLayout = new TableLayoutPanel();
            this.topCameraLayout = new TableLayoutPanel();
            this.centerCameraHeader = new Guna2Button();
            this.centerCamera = new Guna2Panel();
            this.trayHeader = new Guna2Button();
            this.trayLayout = new TableLayoutPanel();
            this.trayTop = new Guna2DataGridView();
            this.trayBottom = new Guna2DataGridView();
            this.trayTopLabel = new Guna2Button();
            this.trayBottomLabel = new Guna2Button();
            this.topCameraHeader = new Guna2Button();
            this.topCamera = new Guna2Panel();
            this.measureItems = new Guna2TextBox();
            this.bTrayLayout = new TableLayoutPanel();
            this.bTrayHeader = new Guna2Button();
            this.bTrayTop = new Guna2DataGridView();
            this.bTrayBottom = new Guna2DataGridView();
            this.bTrayTopLabel = new Guna2Button();
            this.bTrayBottomLabel = new Guna2Button();
            this.processInfoPanel = new Guna2Panel();
            this.processInfoTitle = new Guna2HtmlLabel();
            this.totalTimeLabel = new Guna2HtmlLabel();
            this.totalTimeValue = new Guna2HtmlLabel();
            this.processInfoRightTitle = new Guna2HtmlLabel();
            this.rightTimeLabel = new Guna2HtmlLabel();
            this.rightTimeValue = new Guna2HtmlLabel();
            this.currentFlowLabel = new Guna2HtmlLabel();
            this.currentFlowValue = new Guna2HtmlLabel();
            this.metricLabel = new Guna2HtmlLabel();
            this.showMessageCheck = new Guna2CheckBox();
            this.stopFeedAButton = new Guna2Button();
            this.stopFeedBButton = new Guna2Button();
            this.startButton = new Guna2Button();
            this.stopButton = new Guna2Button();
            this.pauseButton = new Guna2Button();
            this.centerBottomLayout = new TableLayoutPanel();
            this.calibrationProcess = new Guna2TextBox();
            this.stationBProcess = new Guna2TextBox();
            this.stationBTitle = new Guna2HtmlLabel();
            this.stationBNote = new Guna2HtmlLabel();
            this.stationBStatus = new FlowLayoutPanel();
            this.statusB1 = new Guna2Button();
            this.statusB2 = new Guna2Button();
            this.statusB3 = new Guna2Button();
            this.statusB4 = new Guna2Button();
            this.statusB5 = new Guna2Button();
            this.programLog = new Guna2TextBox();
            this.loadCellLayout = new TableLayoutPanel();
            this.loadCell1 = new Guna2Button();
            this.loadCell2 = new Guna2Button();
            this.loadCell3 = new Guna2Button();
            this.loadCell4 = new Guna2Button();
            this.emergencyStop = new Guna2Button();
            this.footerLabel = new Guna2HtmlLabel();
            this.SuspendLayout();
            this.closeControlBox.Name = "closeControlBox";
            this.maximizeControlBox.Name = "maximizeControlBox";
            this.minimizeControlBox.Name = "minimizeControlBox";
            this.rootLayout.Name = "rootLayout";
            this.headerLayout.Name = "headerLayout";
            this.identityLayout.Name = "identityLayout";
            this.bodyLayout.Name = "bodyLayout";
            this.menuLayout.Name = "menuLayout";
            this.headerActions.Name = "headerActions";
            this.logTabsLayout.Name = "logTabsLayout";
            this.brandLabel.Name = "brandLabel";
            this.modelLabel.Name = "modelLabel";
            this.versionLabel.Name = "versionLabel";
            this.loginLabel.Name = "loginLabel";
            this.menuLabel.Name = "menuLabel";
            this.systemLabel.Name = "systemLabel";
            this.clearDispButton.Name = "clearDispButton";
            this.clearLoadButton.Name = "clearLoadButton";
            this.openLogButton.Name = "openLogButton";
            this.programLogTab.Name = "programLogTab";
            this.otherInfoTab.Name = "otherInfoTab";
            this.stationACard.Name = "stationACard";
            this.centerCard.Name = "centerCard";
            this.stationBCard.Name = "stationBCard";
            this.stationALayout.Name = "stationALayout";
            this.centerLayout.Name = "centerLayout";
            this.stationBLayout.Name = "stationBLayout";
            this.stationATitle.Name = "stationATitle";
            this.stationANote.Name = "stationANote";
            this.stationAStatus.Name = "stationAStatus";
            this.statusA1.Name = "statusA1";
            this.statusA2.Name = "statusA2";
            this.statusA3.Name = "statusA3";
            this.statusA4.Name = "statusA4";
            this.statusA5.Name = "statusA5";
            this.pdChartButton.Name = "pdChartButton";
            this.lensTrayButton.Name = "lensTrayButton";
            this.stationAPreviewLayout.Name = "stationAPreviewLayout";
            this.pdPreview.Name = "pdPreview";
            this.stationATrayPreview.Name = "stationATrayPreview";
            this.stationAProcessHeader.Name = "stationAProcessHeader";
            this.stationAProcess.Name = "stationAProcess";
            this.centerTitle.Name = "centerTitle";
            this.laserValue.Name = "laserValue";
            this.centerStationBTitle.Name = "centerStationBTitle";
            this.centerStationBNote.Name = "centerStationBNote";
            this.centerStatus.Name = "centerStatus";
            this.centerStatus1.Name = "centerStatus1";
            this.centerStatus2.Name = "centerStatus2";
            this.centerStatus3.Name = "centerStatus3";
            this.centerStatus4.Name = "centerStatus4";
            this.visionLayout.Name = "visionLayout";
            this.centerCameraLayout.Name = "centerCameraLayout";
            this.topCameraLayout.Name = "topCameraLayout";
            this.centerCameraHeader.Name = "centerCameraHeader";
            this.centerCamera.Name = "centerCamera";
            this.trayHeader.Name = "trayHeader";
            this.trayLayout.Name = "trayLayout";
            this.trayTop.Name = "trayTop";
            this.trayBottom.Name = "trayBottom";
            this.trayTopLabel.Name = "trayTopLabel";
            this.trayBottomLabel.Name = "trayBottomLabel";
            this.topCameraHeader.Name = "topCameraHeader";
            this.topCamera.Name = "topCamera";
            this.measureItems.Name = "measureItems";
            this.bTrayLayout.Name = "bTrayLayout";
            this.bTrayHeader.Name = "bTrayHeader";
            this.bTrayTop.Name = "bTrayTop";
            this.bTrayBottom.Name = "bTrayBottom";
            this.bTrayTopLabel.Name = "bTrayTopLabel";
            this.bTrayBottomLabel.Name = "bTrayBottomLabel";
            this.processInfoPanel.Name = "processInfoPanel";
            this.processInfoTitle.Name = "processInfoTitle";
            this.totalTimeLabel.Name = "totalTimeLabel";
            this.totalTimeValue.Name = "totalTimeValue";
            this.processInfoRightTitle.Name = "processInfoRightTitle";
            this.rightTimeLabel.Name = "rightTimeLabel";
            this.rightTimeValue.Name = "rightTimeValue";
            this.currentFlowLabel.Name = "currentFlowLabel";
            this.currentFlowValue.Name = "currentFlowValue";
            this.metricLabel.Name = "metricLabel";
            this.showMessageCheck.Name = "showMessageCheck";
            this.stopFeedAButton.Name = "stopFeedAButton";
            this.stopFeedBButton.Name = "stopFeedBButton";
            this.startButton.Name = "startButton";
            this.stopButton.Name = "stopButton";
            this.pauseButton.Name = "pauseButton";
            this.centerBottomLayout.Name = "centerBottomLayout";
            this.calibrationProcess.Name = "calibrationProcess";
            this.stationBProcess.Name = "stationBProcess";
            this.stationBTitle.Name = "stationBTitle";
            this.stationBNote.Name = "stationBNote";
            this.stationBStatus.Name = "stationBStatus";
            this.statusB1.Name = "statusB1";
            this.statusB2.Name = "statusB2";
            this.statusB3.Name = "statusB3";
            this.statusB4.Name = "statusB4";
            this.statusB5.Name = "statusB5";
            this.programLog.Name = "programLog";
            this.loadCellLayout.Name = "loadCellLayout";
            this.loadCell1.Name = "loadCell1";
            this.loadCell2.Name = "loadCell2";
            this.loadCell3.Name = "loadCell3";
            this.loadCell4.Name = "loadCell4";
            this.emergencyStop.Name = "emergencyStop";
            this.footerLabel.Name = "footerLabel";

            this.rootLayout.Dock = DockStyle.Fill;
            this.rootLayout.Margin = Padding.Empty;
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 20F));

            this.headerLayout.Dock = DockStyle.Fill;
            this.headerLayout.Padding = new Padding(8, 4, 8, 2);
            this.headerLayout.ColumnCount = 3;
            this.headerLayout.RowCount = 2;
            this.headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 475F));
            this.headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 570F));
            this.headerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            this.headerLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.identityLayout.Dock = DockStyle.Fill;
            this.identityLayout.WrapContents = false;
            this.identityLayout.Margin = Padding.Empty;
            this.identityLayout.Controls.Add(this.brandLabel);
            this.identityLayout.Controls.Add(this.modelLabel);
            this.identityLayout.Controls.Add(this.versionLabel);

            this.menuLayout.Dock = DockStyle.Fill;
            this.menuLayout.WrapContents = false;
            this.menuLayout.Margin = Padding.Empty;
            this.menuLayout.Controls.Add(this.menuLabel);

            this.headerActions.Dock = DockStyle.Fill;
            this.headerActions.FlowDirection = FlowDirection.RightToLeft;
            this.headerActions.WrapContents = false;
            this.headerActions.Margin = Padding.Empty;
            this.headerActions.Controls.Add(this.closeControlBox);
            this.headerActions.Controls.Add(this.maximizeControlBox);
            this.headerActions.Controls.Add(this.minimizeControlBox);
            this.headerActions.Controls.Add(this.openLogButton);
            this.headerActions.Controls.Add(this.clearLoadButton);
            this.headerActions.Controls.Add(this.clearDispButton);

            this.closeControlBox.FillColor = Color.FromArgb(120, 135, 148);
            this.closeControlBox.IconColor = Color.White;
            this.closeControlBox.Size = new Size(34, 28);
            this.closeControlBox.Margin = Padding.Empty;
            this.maximizeControlBox.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MaximizeBox;
            this.maximizeControlBox.FillColor = Color.FromArgb(120, 135, 148);
            this.maximizeControlBox.IconColor = Color.White;
            this.maximizeControlBox.Size = new Size(34, 28);
            this.maximizeControlBox.Margin = Padding.Empty;
            this.minimizeControlBox.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MinimizeBox;
            this.minimizeControlBox.FillColor = Color.FromArgb(120, 135, 148);
            this.minimizeControlBox.IconColor = Color.White;
            this.minimizeControlBox.Size = new Size(34, 28);
            this.minimizeControlBox.Margin = Padding.Empty;

            this.logTabsLayout.Dock = DockStyle.Fill;
            this.logTabsLayout.ColumnCount = 2;
            this.logTabsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.logTabsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.programLogTab.Text = "Program Log";
            this.programLogTab.Dock = DockStyle.Fill;
            this.programLogTab.FillColor = Color.FromArgb(105, 105, 105);
            this.programLogTab.ForeColor = Color.Black;
            this.programLogTab.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            this.programLogTab.BorderRadius = 0;
            this.otherInfoTab.Text = "Other Information";
            this.otherInfoTab.Dock = DockStyle.Fill;
            this.otherInfoTab.FillColor = Color.FromArgb(238, 238, 238);
            this.otherInfoTab.ForeColor = Color.Silver;
            this.otherInfoTab.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            this.otherInfoTab.BorderRadius = 0;
            this.logTabsLayout.Controls.Add(this.programLogTab, 0, 0);
            this.logTabsLayout.Controls.Add(this.otherInfoTab, 1, 0);

            this.brandLabel.Text = "oToPUs";
            this.brandLabel.Font = new Font("Segoe UI", 19F, FontStyle.Bold);
            this.brandLabel.ForeColor = Color.FromArgb(200, 28, 38);
            this.brandLabel.BackColor = Color.Transparent;
            this.brandLabel.Margin = new Padding(0, 1, 10, 0);
            this.modelLabel.Text = "Nova AA-2";
            this.modelLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold | FontStyle.Italic);
            this.modelLabel.Margin = new Padding(10, 9, 12, 0);
            this.versionLabel.Text = "Ver. 1.1.0.7   Release Date: 2026/8/31";
            this.versionLabel.Font = new Font("Segoe UI", 7F, FontStyle.Bold);
            this.versionLabel.Margin = new Padding(0, 4, 0, 0);
            this.loginLabel.Text = "Login Level : Operator<br>License expiration date : 12/31/2026";
            this.loginLabel.Dock = DockStyle.Fill;
            this.loginLabel.Font = new Font("Segoe UI", 8F, FontStyle.Bold | FontStyle.Italic);
            this.loginLabel.ForeColor = Color.Maroon;
            this.loginLabel.TextAlignment = ContentAlignment.MiddleLeft;
            this.menuLabel.Text = "LOGIN       CONFIG       EDITOR       SHOW LOG";
            this.menuLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this.menuLabel.Margin = new Padding(5, 7, 0, 0);
            this.systemLabel.Text = "●  ●  ●      EMG       CDA       LEFT       RIGHT";
            this.systemLabel.Dock = DockStyle.Fill;
            this.systemLabel.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            this.systemLabel.ForeColor = Color.Gray;
            this.systemLabel.TextAlignment = ContentAlignment.MiddleLeft;

            this.clearDispButton.Text = "Clear Disp. Running Status"; this.clearDispButton.Width = 158; this.clearDispButton.Height = 25; this.clearDispButton.FillColor = Color.White; this.clearDispButton.ForeColor = Color.FromArgb(50, 58, 65); this.clearDispButton.BorderColor = Color.FromArgb(145, 155, 165); this.clearDispButton.BorderThickness = 1; this.clearDispButton.BorderRadius = 3; this.clearDispButton.Margin = new Padding(3, 5, 3, 0);
            this.clearLoadButton.Text = "Clear Loadcell Running Status"; this.clearLoadButton.Width = 168; this.clearLoadButton.Height = 25; this.clearLoadButton.FillColor = Color.White; this.clearLoadButton.ForeColor = Color.FromArgb(50, 58, 65); this.clearLoadButton.BorderColor = Color.FromArgb(145, 155, 165); this.clearLoadButton.BorderThickness = 1; this.clearLoadButton.BorderRadius = 3; this.clearLoadButton.Margin = new Padding(3, 5, 3, 0);
            this.openLogButton.Text = "Open log File"; this.openLogButton.Width = 90; this.openLogButton.Height = 25; this.openLogButton.FillColor = Color.White; this.openLogButton.ForeColor = Color.FromArgb(50, 58, 65); this.openLogButton.BorderColor = Color.FromArgb(145, 155, 165); this.openLogButton.BorderThickness = 1; this.openLogButton.BorderRadius = 3; this.openLogButton.Margin = new Padding(3, 5, 3, 0);

            this.headerLayout.Controls.Add(this.identityLayout, 0, 0);
            this.headerLayout.Controls.Add(this.loginLabel, 1, 0);
            this.headerLayout.Controls.Add(this.headerActions, 2, 0);
            this.headerLayout.Controls.Add(this.menuLayout, 0, 1);
            this.headerLayout.Controls.Add(this.systemLabel, 1, 1);
            this.headerLayout.Controls.Add(this.logTabsLayout, 2, 1);

            this.bodyLayout.Dock = DockStyle.Fill;
            this.bodyLayout.Padding = new Padding(8, 0, 8, 0);
            this.bodyLayout.ColumnCount = 3;
            this.bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 24F));
            this.bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 46F));
            this.bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 30F));
            this.bodyLayout.Controls.Add(this.stationACard, 0, 0);
            this.bodyLayout.Controls.Add(this.centerCard, 1, 0);
            this.bodyLayout.Controls.Add(this.stationBCard, 2, 0);

            this.stationACard.Dock = DockStyle.Fill; this.stationACard.FillColor = Color.White; this.stationACard.BorderColor = Color.FromArgb(199, 207, 215); this.stationACard.BorderThickness = 1; this.stationACard.BorderRadius = 4; this.stationACard.Padding = new Padding(2); this.stationACard.Margin = new Padding(0, 0, 5, 0);
            this.centerCard.Dock = DockStyle.Fill; this.centerCard.FillColor = Color.White; this.centerCard.BorderColor = Color.FromArgb(199, 207, 215); this.centerCard.BorderThickness = 1; this.centerCard.BorderRadius = 4; this.centerCard.Padding = new Padding(2); this.centerCard.Margin = new Padding(0, 0, 5, 0);
            this.stationBCard.Dock = DockStyle.Fill; this.stationBCard.FillColor = Color.White; this.stationBCard.BorderColor = Color.FromArgb(199, 207, 215); this.stationBCard.BorderThickness = 1; this.stationBCard.BorderRadius = 4; this.stationBCard.Padding = new Padding(2); this.stationBCard.Margin = Padding.Empty;
            this.stationACard.Controls.Add(this.stationALayout);
            this.centerCard.Controls.Add(this.centerLayout);
            this.stationBCard.Controls.Add(this.stationBLayout);

            this.stationALayout.Dock = DockStyle.Fill;
            this.stationALayout.ColumnCount = 2;
            this.stationALayout.RowCount = 6;
            this.stationALayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.stationALayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.stationALayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.stationALayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            this.stationALayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.stationALayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            this.stationALayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.stationALayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.stationATitle.Text = "STATION A"; this.stationATitle.Dock = DockStyle.Fill; this.stationATitle.FillColor = Color.FromArgb(91, 164, 231); this.stationATitle.ForeColor = Color.FromArgb(0, 65, 112); this.stationATitle.Font = new Font("Segoe UI", 13F, FontStyle.Italic); this.stationATitle.BorderRadius = 0;
            this.stationANote.Text = "No iCSM"; this.stationANote.Dock = DockStyle.Fill; this.stationANote.FillColor = Color.FromArgb(234, 234, 234); this.stationANote.ForeColor = Color.FromArgb(40, 55, 65); this.stationANote.Font = new Font("Segoe UI", 9F, FontStyle.Italic); this.stationANote.BorderRadius = 0;
            this.stationAStatus.Dock = DockStyle.Fill;
            this.stationAStatus.WrapContents = true;
            this.stationAStatus.Margin = Padding.Empty;
            this.statusA1.Text = "●  SS L1_LS L1"; this.statusA2.Text = "●  Left Vacuum"; this.statusA3.Text = "●  Right Vacuum"; this.statusA4.Text = "●  Front Curing"; this.statusA5.Text = "●  Rear Curing";
            this.statusA1.AutoSize = true; this.statusA2.AutoSize = true; this.statusA3.AutoSize = true; this.statusA4.AutoSize = true; this.statusA5.AutoSize = true;
            this.statusA1.FillColor = Color.Transparent; this.statusA2.FillColor = Color.Transparent; this.statusA3.FillColor = Color.Transparent; this.statusA4.FillColor = Color.Transparent; this.statusA5.FillColor = Color.Transparent;
            this.statusA1.ForeColor = Color.LimeGreen; this.statusA2.ForeColor = Color.LimeGreen; this.statusA3.ForeColor = Color.LimeGreen; this.statusA4.ForeColor = Color.LimeGreen; this.statusA5.ForeColor = Color.LimeGreen;
            this.statusA1.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.statusA2.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.statusA3.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.statusA4.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.statusA5.Font = new Font("Segoe UI", 7F, FontStyle.Bold);
            this.stationAStatus.Controls.AddRange(new Control[] { this.statusA1, this.statusA2, this.statusA3, this.statusA4, this.statusA5 });
            this.pdChartButton.Text = "PD CHART       ▼"; this.pdChartButton.Dock = DockStyle.Fill; this.pdChartButton.FillColor = Color.White; this.pdChartButton.ForeColor = Color.FromArgb(55, 75, 90); this.pdChartButton.BorderColor = Color.FromArgb(190, 198, 207); this.pdChartButton.BorderThickness = 1; this.pdChartButton.BorderRadius = 3;
            this.lensTrayButton.Text = "A LENS TRAY       ↻"; this.lensTrayButton.Dock = DockStyle.Fill; this.lensTrayButton.FillColor = Color.White; this.lensTrayButton.ForeColor = Color.FromArgb(91, 164, 231); this.lensTrayButton.BorderColor = Color.FromArgb(91, 164, 231); this.lensTrayButton.BorderThickness = 1; this.lensTrayButton.BorderRadius = 3;
            this.stationAPreviewLayout.Dock = DockStyle.Fill;
            this.stationAPreviewLayout.ColumnCount = 2;
            this.stationAPreviewLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.stationAPreviewLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.pdPreview.Dock = DockStyle.Fill;
            this.pdPreview.FillColor = Color.White;
            this.pdPreview.BorderColor = Color.FromArgb(180, 190, 200);
            this.pdPreview.BorderThickness = 1;
            this.pdPreview.Margin = new Padding(2);
            this.stationATrayPreview.Dock = DockStyle.Fill;
            this.stationATrayPreview.BackgroundColor = Color.FromArgb(210, 210, 210);
            this.stationATrayPreview.GridColor = Color.FromArgb(235, 235, 235);
            this.stationATrayPreview.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.stationATrayPreview.ColumnHeadersVisible = false;
            this.stationATrayPreview.RowHeadersVisible = false;
            this.stationATrayPreview.AllowUserToAddRows = false;
            this.stationATrayPreview.ColumnCount = 6;
            this.stationATrayPreview.RowCount = 1;
            this.stationATrayPreview.DefaultCellStyle.BackColor = Color.FromArgb(205, 205, 205);
            this.stationATrayPreview.DefaultCellStyle.SelectionBackColor = Color.FromArgb(205, 205, 205);
            this.stationAPreviewLayout.Controls.Add(this.pdPreview, 0, 0);
            this.stationAPreviewLayout.Controls.Add(this.stationATrayPreview, 1, 0);
            this.stationAProcess.Dock = DockStyle.Fill;
            this.stationAProcess.Multiline = true;
            this.stationAProcess.ReadOnly = true;
            this.stationAProcess.ScrollBars = ScrollBars.Vertical;
            this.stationAProcess.Font = new Font("Segoe UI", 8F);
            this.stationAProcess.BorderColor = Color.FromArgb(175, 188, 200);
            this.stationAProcess.BorderRadius = 3;
            this.stationAProcess.Text = "#51 - Wet Active Align L1 L2\r\n#52 - Shift on cure offset\r\n#53 - UV Process Snap\r\n#54 - Get PD Value After Curing\r\n      #1 - Get PD Value [FINISH]\r\n      #2 - [Scan] L2 Line X\r\n      #3 - Get PD Value\r\n      #4 - [Scan] L2 Line Z\r\n      #5 - Get PD Value\r\n      #6 - [Scan] L2 Line Y\r\n      #7 - Get PD Value\r\n      #8 - Check line scan stop condition 1\r\n      #9 - Check line scan stop condition 2\r\n      #10 - [Scan] L2 Line X final\r\n      #11 - Get PD Value\r\n      #12 - [Scan] L2 Line Z final\r\n#55 - Release L1 and move rear PUT\r\n#56 - Get PD Value After Release\r\n#57 - Move L2 lens to safe position\r\n#58 - Close SOA0 Config\r\n#59 - Pick Up SS_L1 On Top Tray\r\n#60 - All station Servo on\r\n#61 - Set SOA1 Config\r\n#62 - Vision Align SOA1 iCSM\r\n#63 - Vision Align-L1 Lens\r\n#64 - Active Align-L1 Lens\r\n#65 - Move L2 to teach position\r\n#66 - Active Align-L2 Lens\r\n#67 - Active Align concurrent-L1 L2\r\n#68 - Epoxy Dispense L1\r\n#69 - Wet Active Align L1 L2";
            this.stationAProcessHeader.Text = "↕   Station A Process  [Process Station A 20260713]";
            this.stationAProcessHeader.Dock = DockStyle.Fill;
            this.stationAProcessHeader.FillColor = Color.White;
            this.stationAProcessHeader.ForeColor = Color.FromArgb(70, 92, 110);
            this.stationAProcessHeader.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            this.stationAProcessHeader.TextAlign = HorizontalAlignment.Left;
            this.stationAProcessHeader.BorderColor = Color.FromArgb(91, 164, 231);
            this.stationAProcessHeader.BorderThickness = 1;
            this.stationALayout.Controls.Add(this.stationATitle, 0, 0);
            this.stationALayout.Controls.Add(this.stationANote, 1, 0);
            this.stationALayout.Controls.Add(this.stationAStatus, 0, 1);
            this.stationALayout.SetColumnSpan(this.stationAStatus, 2);
            this.stationALayout.Controls.Add(this.pdChartButton, 0, 2);
            this.stationALayout.Controls.Add(this.lensTrayButton, 1, 2);
            this.stationALayout.Controls.Add(this.stationAPreviewLayout, 0, 3);
            this.stationALayout.SetColumnSpan(this.stationAPreviewLayout, 2);
            this.stationALayout.Controls.Add(this.stationAProcessHeader, 0, 4);
            this.stationALayout.SetColumnSpan(this.stationAProcessHeader, 2);
            this.stationALayout.Controls.Add(this.stationAProcess, 0, 5);
            this.stationALayout.SetColumnSpan(this.stationAProcess, 2);
            this.centerLayout.Dock = DockStyle.Fill;
            this.centerLayout.ColumnCount = 4;
            this.centerLayout.RowCount = 5;
            this.centerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 26F));
            this.centerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
            this.centerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 26F));
            this.centerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 30F));
            this.centerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.centerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            this.centerLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 62F));
            this.centerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 126F));
            this.centerLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 38F));
            this.centerTitle.Text = "CENTER"; this.centerTitle.Dock = DockStyle.Fill; this.centerTitle.FillColor = Color.FromArgb(91, 164, 231); this.centerTitle.ForeColor = Color.FromArgb(0, 65, 112); this.centerTitle.Font = new Font("Segoe UI", 13F, FontStyle.Italic); this.centerTitle.BorderRadius = 0;
            this.laserValue.Text = "Laser : 0.0000"; this.laserValue.Dock = DockStyle.Fill; this.laserValue.FillColor = Color.FromArgb(234, 234, 234); this.laserValue.Font = new Font("Segoe UI", 8F, FontStyle.Bold); this.laserValue.TextAlign = HorizontalAlignment.Left; this.laserValue.BorderRadius = 0;
            this.laserValue.ForeColor = Color.Green;
            this.centerStationBTitle.Text = "STATION B";
            this.centerStationBTitle.Dock = DockStyle.Fill;
            this.centerStationBTitle.FillColor = Color.FromArgb(91, 164, 231);
            this.centerStationBTitle.ForeColor = Color.FromArgb(0, 65, 112);
            this.centerStationBTitle.Font = new Font("Segoe UI", 13F, FontStyle.Italic);
            this.centerStationBTitle.BorderRadius = 0;
            this.centerStationBNote.Text = "No iCSM";
            this.centerStationBNote.Dock = DockStyle.Fill;
            this.centerStationBNote.FillColor = Color.FromArgb(234, 234, 234);
            this.centerStationBNote.Font = new Font("Segoe UI", 9F, FontStyle.Italic);
            this.centerStationBNote.BorderRadius = 0;
            this.centerStatus.Dock = DockStyle.Fill;
            this.centerStatus.WrapContents = true;
            this.centerStatus.Margin = Padding.Empty;
            this.centerStatus1.Text = "●  Gripper Down"; this.centerStatus2.Text = "●  Gripper Close"; this.centerStatus3.Text = "●  A Stage Vacuum"; this.centerStatus4.Text = "●  B Stage Vacuum";
            this.centerStatus1.AutoSize = true; this.centerStatus2.AutoSize = true; this.centerStatus3.AutoSize = true; this.centerStatus4.AutoSize = true;
            this.centerStatus1.FillColor = Color.Transparent; this.centerStatus2.FillColor = Color.Transparent; this.centerStatus3.FillColor = Color.Transparent; this.centerStatus4.FillColor = Color.Transparent;
            this.centerStatus1.ForeColor = Color.LimeGreen; this.centerStatus2.ForeColor = Color.LimeGreen; this.centerStatus3.ForeColor = Color.LimeGreen; this.centerStatus4.ForeColor = Color.LimeGreen;
            this.centerStatus1.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.centerStatus2.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.centerStatus3.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.centerStatus4.Font = new Font("Segoe UI", 7F, FontStyle.Bold);
            this.centerStatus.Controls.AddRange(new Control[] { this.centerStatus1, this.centerStatus2, this.centerStatus3, this.centerStatus4 });
            this.centerLayout.Controls.Add(this.centerTitle, 0, 0);
            this.centerLayout.Controls.Add(this.laserValue, 1, 0);
            this.centerLayout.Controls.Add(this.centerStationBTitle, 2, 0);
            this.centerLayout.Controls.Add(this.centerStationBNote, 3, 0);
            this.centerLayout.Controls.Add(this.centerStatus, 0, 1);
            this.centerLayout.SetColumnSpan(this.centerStatus, 2);
            this.centerLayout.Controls.Add(this.stationBStatus, 2, 1);
            this.centerLayout.SetColumnSpan(this.stationBStatus, 2);

            this.visionLayout.Dock = DockStyle.Fill;
            this.visionLayout.ColumnCount = 4;
            this.visionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 26F));
            this.visionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
            this.visionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 26F));
            this.visionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 30F));
            this.centerCameraLayout.Dock = DockStyle.Fill;
            this.centerCameraLayout.RowCount = 2;
            this.centerCameraLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
            this.centerCameraLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.topCameraLayout.Dock = DockStyle.Fill;
            this.topCameraLayout.RowCount = 3;
            this.topCameraLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
            this.topCameraLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 58F));
            this.topCameraLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 42F));
            this.centerCameraHeader.Text = "CENTER CAMERA       ▼"; this.centerCameraHeader.Dock = DockStyle.Top; this.centerCameraHeader.Height = 34; this.centerCameraHeader.FillColor = Color.White; this.centerCameraHeader.ForeColor = Color.FromArgb(55, 75, 90); this.centerCameraHeader.BorderColor = Color.FromArgb(91, 164, 231); this.centerCameraHeader.BorderThickness = 1;
            this.trayHeader.Text = "iCSM TRAY       ↻"; this.trayHeader.Dock = DockStyle.Fill; this.trayHeader.FillColor = Color.White; this.trayHeader.ForeColor = Color.FromArgb(91, 164, 231); this.trayHeader.BorderColor = Color.FromArgb(91, 164, 231); this.trayHeader.BorderThickness = 1;
            this.topCameraHeader.Text = "TOP VISION CAMERA       ▼"; this.topCameraHeader.Dock = DockStyle.Top; this.topCameraHeader.Height = 34; this.topCameraHeader.FillColor = Color.White; this.topCameraHeader.ForeColor = Color.FromArgb(55, 75, 90); this.topCameraHeader.BorderColor = Color.FromArgb(91, 164, 231); this.topCameraHeader.BorderThickness = 1;
            this.centerCamera.Dock = DockStyle.Fill;
            this.centerCamera.FillColor = Color.FromArgb(58, 58, 58);
            this.centerCamera.BorderRadius = 4;
            this.centerCamera.Margin = new Padding(4);
            this.topCamera.Dock = DockStyle.Fill;
            this.topCamera.FillColor = Color.FromArgb(58, 58, 58);
            this.topCamera.BorderRadius = 4;
            this.topCamera.Margin = new Padding(4);
            this.trayLayout.Dock = DockStyle.Fill;
            this.trayLayout.RowCount = 5;
            this.trayLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
            this.trayLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 18F));
            this.trayLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            this.trayLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 18F));
            this.trayLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            this.trayLayout.Controls.Add(this.trayHeader, 0, 0);
            this.trayTopLabel.Text = "iCSM TOP"; this.trayTopLabel.Dock = DockStyle.Fill; this.trayTopLabel.FillColor = Color.White; this.trayTopLabel.ForeColor = Color.FromArgb(80, 80, 80); this.trayTopLabel.Font = new Font("Segoe UI", 7F);
            this.trayBottomLabel.Text = "iCSM BOTTOM"; this.trayBottomLabel.Dock = DockStyle.Fill; this.trayBottomLabel.FillColor = Color.White; this.trayBottomLabel.ForeColor = Color.FromArgb(80, 80, 80); this.trayBottomLabel.Font = new Font("Segoe UI", 7F);
            this.trayLayout.Controls.Add(this.trayTopLabel, 0, 1);
            this.trayLayout.Controls.Add(this.trayTop, 0, 2);
            this.trayLayout.Controls.Add(this.trayBottomLabel, 0, 3);
            this.trayLayout.Controls.Add(this.trayBottom, 0, 4);
            this.trayTop.Dock = DockStyle.Fill; this.trayTop.BackgroundColor = Color.FromArgb(96, 147, 225); this.trayTop.GridColor = Color.FromArgb(190, 214, 239); this.trayTop.BorderStyle = System.Windows.Forms.BorderStyle.None; this.trayTop.ColumnHeadersVisible = false; this.trayTop.RowHeadersVisible = false; this.trayTop.AllowUserToAddRows = false; this.trayTop.ColumnCount = 6; this.trayTop.RowCount = 6;
            this.trayTop.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; this.trayTop.DefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225); this.trayTop.DefaultCellStyle.SelectionBackColor = Color.FromArgb(96, 147, 225); this.trayTop.RowsDefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225); this.trayTop.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225);
            this.trayTop.CellBorderStyle = DataGridViewCellBorderStyle.Single;
            this.trayBottom.Dock = DockStyle.Fill; this.trayBottom.BackgroundColor = Color.FromArgb(96, 147, 225); this.trayBottom.GridColor = Color.FromArgb(190, 214, 239); this.trayBottom.BorderStyle = System.Windows.Forms.BorderStyle.None; this.trayBottom.ColumnHeadersVisible = false; this.trayBottom.RowHeadersVisible = false; this.trayBottom.AllowUserToAddRows = false; this.trayBottom.ColumnCount = 6; this.trayBottom.RowCount = 6;
            this.trayBottom.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; this.trayBottom.DefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225); this.trayBottom.DefaultCellStyle.SelectionBackColor = Color.FromArgb(96, 147, 225); this.trayBottom.RowsDefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225); this.trayBottom.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225);
            this.trayBottom.CellBorderStyle = DataGridViewCellBorderStyle.Single;
            this.centerCameraLayout.Controls.Add(this.centerCameraHeader, 0, 0);
            this.centerCameraLayout.Controls.Add(this.centerCamera, 0, 1);
            this.visionLayout.Controls.Add(this.centerCameraLayout, 0, 0);
            this.visionLayout.Controls.Add(this.trayLayout, 1, 0);
            this.measureItems.Dock = DockStyle.Bottom;
            this.measureItems.Height = 135;
            this.measureItems.Multiline = true;
            this.measureItems.ReadOnly = true;
            this.measureItems.FillColor = Color.White;
            this.measureItems.BorderColor = Color.FromArgb(175, 188, 200);
            this.measureItems.Font = new Font("Segoe UI", 7.5F);
            this.measureItems.Text = "Measure Items                 Result\r\nBarcode\r\nLaser B Max\r\nLaser A Max\r\nSOA0 Max\r\nSOA1 Max\r\nSOA2 Max";
            this.topCameraLayout.Controls.Add(this.topCameraHeader, 0, 0);
            this.topCameraLayout.Controls.Add(this.topCamera, 0, 1);
            this.topCameraLayout.Controls.Add(this.measureItems, 0, 2);
            this.visionLayout.Controls.Add(this.topCameraLayout, 2, 0);
            this.bTrayLayout.Dock = DockStyle.Fill;
            this.bTrayLayout.RowCount = 5;
            this.bTrayLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
            this.bTrayLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 18F));
            this.bTrayLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            this.bTrayLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 18F));
            this.bTrayLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            this.bTrayHeader.Text = "B LENS TRAY       ↻";
            this.bTrayHeader.Dock = DockStyle.Fill;
            this.bTrayHeader.FillColor = Color.White;
            this.bTrayHeader.ForeColor = Color.FromArgb(91, 164, 231);
            this.bTrayHeader.BorderColor = Color.FromArgb(91, 164, 231);
            this.bTrayHeader.BorderThickness = 1;
            this.bTrayTop.Dock = DockStyle.Fill;
            this.bTrayTop.BackgroundColor = Color.FromArgb(96, 147, 225);
            this.bTrayTop.GridColor = Color.FromArgb(190, 214, 239);
            this.bTrayTop.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bTrayTop.ColumnHeadersVisible = false;
            this.bTrayTop.RowHeadersVisible = false;
            this.bTrayTop.AllowUserToAddRows = false;
            this.bTrayTop.ColumnCount = 10;
            this.bTrayTop.RowCount = 7;
            this.bTrayTop.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; this.bTrayTop.DefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225); this.bTrayTop.DefaultCellStyle.SelectionBackColor = Color.FromArgb(96, 147, 225); this.bTrayTop.RowsDefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225); this.bTrayTop.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225);
            this.bTrayBottom.Dock = DockStyle.Fill;
            this.bTrayBottom.BackgroundColor = Color.FromArgb(96, 147, 225);
            this.bTrayBottom.GridColor = Color.FromArgb(190, 214, 239);
            this.bTrayBottom.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bTrayBottom.ColumnHeadersVisible = false;
            this.bTrayBottom.RowHeadersVisible = false;
            this.bTrayBottom.AllowUserToAddRows = false;
            this.bTrayBottom.ColumnCount = 10;
            this.bTrayBottom.RowCount = 7;
            this.bTrayBottom.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; this.bTrayBottom.DefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225); this.bTrayBottom.DefaultCellStyle.SelectionBackColor = Color.FromArgb(96, 147, 225); this.bTrayBottom.RowsDefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225); this.bTrayBottom.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(96, 147, 225);
            this.bTrayTopLabel.Text = "SS L2"; this.bTrayTopLabel.Dock = DockStyle.Fill; this.bTrayTopLabel.FillColor = Color.White; this.bTrayTopLabel.ForeColor = Color.FromArgb(135, 85, 45); this.bTrayTopLabel.Font = new Font("Segoe UI", 7F);
            this.bTrayBottomLabel.Text = "LS L2"; this.bTrayBottomLabel.Dock = DockStyle.Fill; this.bTrayBottomLabel.FillColor = Color.White; this.bTrayBottomLabel.ForeColor = Color.FromArgb(135, 85, 45); this.bTrayBottomLabel.Font = new Font("Segoe UI", 7F);
            this.bTrayLayout.Controls.Add(this.bTrayHeader, 0, 0);
            this.bTrayLayout.Controls.Add(this.bTrayTopLabel, 0, 1);
            this.bTrayLayout.Controls.Add(this.bTrayTop, 0, 2);
            this.bTrayLayout.Controls.Add(this.bTrayBottomLabel, 0, 3);
            this.bTrayLayout.Controls.Add(this.bTrayBottom, 0, 4);
            this.bTrayTop.CellBorderStyle = DataGridViewCellBorderStyle.Single;
            this.bTrayBottom.CellBorderStyle = DataGridViewCellBorderStyle.Single;
            this.visionLayout.Controls.Add(this.bTrayLayout, 3, 0);
            this.centerLayout.Controls.Add(this.visionLayout, 0, 2);
            this.centerLayout.SetColumnSpan(this.visionLayout, 4);

            this.processInfoPanel.Dock = DockStyle.Fill;
            this.processInfoPanel.FillColor = Color.White;
            this.processInfoPanel.BorderColor = Color.FromArgb(195, 205, 215);
            this.processInfoPanel.BorderThickness = 1;
            this.processInfoTitle.Text = "PROCESS INFO.";
            this.processInfoTitle.Font = new Font("Segoe UI", 11F, FontStyle.Italic);
            this.processInfoTitle.Location = new Point(8, 7);
            this.totalTimeLabel.Text = "Auto Run Proc. Time";
            this.totalTimeLabel.Font = new Font("Segoe UI", 9F, FontStyle.Italic);
            this.totalTimeLabel.Location = new Point(8, 34);
            this.totalTimeValue.Text = "000.00 sec.";
            this.totalTimeValue.BackColor = Color.FromArgb(255, 176, 0);
            this.totalTimeValue.Font = new Font("Segoe UI", 9F, FontStyle.Italic);
            this.totalTimeValue.TextAlignment = ContentAlignment.MiddleRight;
            this.totalTimeValue.AutoSize = false;
            this.totalTimeValue.Location = new Point(125, 32);
            this.totalTimeValue.Size = new Size(195, 24);
            this.processInfoRightTitle.Text = "PROCESS INFO.";
            this.processInfoRightTitle.Font = new Font("Segoe UI", 11F, FontStyle.Italic);
            this.processInfoRightTitle.Location = new Point(330, 7);
            this.rightTimeLabel.Text = "Total Proc. Time";
            this.rightTimeLabel.Font = new Font("Segoe UI", 9F, FontStyle.Italic);
            this.rightTimeLabel.Location = new Point(330, 34);
            this.rightTimeValue.Text = "000.00 sec.";
            this.rightTimeValue.AutoSize = false;
            this.rightTimeValue.BackColor = Color.FromArgb(255, 176, 0);
            this.rightTimeValue.Font = new Font("Segoe UI", 9F, FontStyle.Italic);
            this.rightTimeValue.TextAlignment = ContentAlignment.MiddleRight;
            this.rightTimeValue.Location = new Point(435, 32);
            this.rightTimeValue.Size = new Size(200, 24);
            this.currentFlowLabel.Text = "Cur. Flow";
            this.currentFlowLabel.Font = new Font("Segoe UI", 8F, FontStyle.Italic);
            this.currentFlowLabel.Location = new Point(330, 61);
            this.currentFlowValue.Text = "Process Name";
            this.currentFlowValue.AutoSize = false;
            this.currentFlowValue.BackColor = Color.FromArgb(225, 225, 225);
            this.currentFlowValue.TextAlignment = ContentAlignment.MiddleRight;
            this.currentFlowValue.Location = new Point(400, 59);
            this.currentFlowValue.Size = new Size(235, 22);
            this.metricLabel.Text = "Socket :  0.00       SOA :  0.00       Laser :  0.00";
            this.metricLabel.ForeColor = Color.Red;
            this.metricLabel.Font = new Font("Segoe UI", 8F, FontStyle.Bold | FontStyle.Italic);
            this.metricLabel.Location = new Point(330, 92);
            this.startButton.Text = "▶  START"; this.startButton.Location = new Point(8, 72); this.startButton.Size = new Size(95, 34); this.startButton.FillColor = Color.White; this.startButton.ForeColor = Color.FromArgb(85, 165, 230); this.startButton.BorderColor = Color.FromArgb(85, 165, 230); this.startButton.BorderThickness = 1; this.startButton.BorderRadius = 16; this.startButton.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            this.stopButton.Text = "■  STOP"; this.stopButton.Location = new Point(110, 72); this.stopButton.Size = new Size(95, 34); this.stopButton.FillColor = Color.White; this.stopButton.ForeColor = Color.Gray; this.stopButton.BorderColor = Color.Gray; this.stopButton.BorderThickness = 1; this.stopButton.BorderRadius = 16; this.stopButton.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            this.pauseButton.Text = "Ⅱ  PAUSE"; this.pauseButton.Location = new Point(212, 72); this.pauseButton.Size = new Size(95, 34); this.pauseButton.FillColor = Color.White; this.pauseButton.ForeColor = Color.FromArgb(85, 165, 230); this.pauseButton.BorderColor = Color.FromArgb(85, 165, 230); this.pauseButton.BorderThickness = 1; this.pauseButton.BorderRadius = 16; this.pauseButton.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            this.showMessageCheck.Text = "Show Message When Start Station On Auto Run";
            this.showMessageCheck.Font = new Font("Segoe UI", 7F);
            this.showMessageCheck.Location = new Point(8, 108);
            this.stopFeedAButton.Text = "STOP FEEDING STATION A";
            this.stopFeedAButton.Location = new Point(185, 106);
            this.stopFeedAButton.Size = new Size(175, 20);
            this.stopFeedAButton.FillColor = Color.FromArgb(225, 225, 225);
            this.stopFeedAButton.ForeColor = Color.Gray;
            this.stopFeedAButton.Font = new Font("Segoe UI", 7F, FontStyle.Bold);
            this.stopFeedBButton.Text = "STOP FEEDING STATION B";
            this.stopFeedBButton.Location = new Point(365, 106);
            this.stopFeedBButton.Size = new Size(175, 20);
            this.stopFeedBButton.FillColor = Color.FromArgb(225, 225, 225);
            this.stopFeedBButton.ForeColor = Color.Gray;
            this.stopFeedBButton.Font = new Font("Segoe UI", 7F, FontStyle.Bold);
            this.processInfoPanel.Controls.AddRange(new Control[] { this.processInfoTitle, this.totalTimeLabel, this.totalTimeValue, this.processInfoRightTitle, this.rightTimeLabel, this.rightTimeValue, this.currentFlowLabel, this.currentFlowValue, this.metricLabel, this.startButton, this.stopButton, this.pauseButton, this.showMessageCheck, this.stopFeedAButton, this.stopFeedBButton });
            this.centerLayout.Controls.Add(this.processInfoPanel, 0, 3);
            this.centerLayout.SetColumnSpan(this.processInfoPanel, 4);

            this.centerBottomLayout.Dock = DockStyle.Fill;
            this.centerBottomLayout.ColumnCount = 2;
            this.centerBottomLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 46F));
            this.centerBottomLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 54F));
            this.calibrationProcess.Dock = DockStyle.Fill;
            this.calibrationProcess.Multiline = true;
            this.calibrationProcess.ReadOnly = true;
            this.calibrationProcess.BorderColor = Color.FromArgb(91, 164, 231);
            this.calibrationProcess.Text = "CALIBRATION\r\n#1 - Station A Needle Calibration\r\n#2 - Station B Needle Calibration\r\n#3 - Station A Dispensing Calibration\r\n#4 - Station B Dispensing Calibration\r\n#5 - Station A Laser and Jig\r\n#6 - Station B Laser and Jig";
            this.stationBProcess.Dock = DockStyle.Fill;
            this.stationBProcess.Multiline = true;
            this.stationBProcess.ReadOnly = true;
            this.stationBProcess.BorderColor = Color.FromArgb(91, 164, 231);
            this.stationBProcess.Text = "STATION B PROCESS  [ATLAS L2 30-07-2026]\r\n#1 - Start Process\r\n#2 - Block pin height measurement\r\n#3 - Servo on\r\n#4 - Reset AA Counter\r\n#5 - Set Laser B Config\r\n#6 - Vision Align Laser B iCSM";
            this.centerBottomLayout.Controls.Add(this.calibrationProcess, 0, 0);
            this.centerBottomLayout.Controls.Add(this.stationBProcess, 1, 0);
            this.centerLayout.Controls.Add(this.centerBottomLayout, 0, 4);
            this.centerLayout.SetColumnSpan(this.centerBottomLayout, 4);
            this.stationBLayout.Dock = DockStyle.Fill;
            this.stationBLayout.ColumnCount = 1;
            this.stationBLayout.RowCount = 2;
            this.stationBLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.stationBLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 94F));
            this.stationBTitle.Text = "STATION B"; this.stationBTitle.Dock = DockStyle.Fill; this.stationBTitle.AutoSize = false; this.stationBTitle.BackColor = Color.FromArgb(91, 164, 231); this.stationBTitle.ForeColor = Color.FromArgb(0, 65, 112); this.stationBTitle.Font = new Font("Segoe UI", 13F, FontStyle.Italic); this.stationBTitle.TextAlignment = ContentAlignment.MiddleCenter;
            this.stationBNote.Text = "No iCSM"; this.stationBNote.Dock = DockStyle.Fill; this.stationBNote.AutoSize = false; this.stationBNote.BackColor = Color.FromArgb(234, 234, 234); this.stationBNote.Font = new Font("Segoe UI", 9F, FontStyle.Italic); this.stationBNote.TextAlignment = ContentAlignment.MiddleCenter;
            this.stationBStatus.Dock = DockStyle.Fill;
            this.stationBStatus.WrapContents = true;
            this.stationBStatus.Margin = Padding.Empty;
            this.statusB1.Text = "●  SS_L2"; this.statusB2.Text = "●  LS_L2"; this.statusB3.Text = "●  Left Vacuum"; this.statusB4.Text = "●  Right Vacuum"; this.statusB5.Text = "●  Front Curing";
            this.statusB1.AutoSize = true; this.statusB2.AutoSize = true; this.statusB3.AutoSize = true; this.statusB4.AutoSize = true; this.statusB5.AutoSize = true;
            this.statusB1.FillColor = Color.Transparent; this.statusB2.FillColor = Color.Transparent; this.statusB3.FillColor = Color.Transparent; this.statusB4.FillColor = Color.Transparent; this.statusB5.FillColor = Color.Transparent;
            this.statusB1.ForeColor = Color.LimeGreen; this.statusB2.ForeColor = Color.LimeGreen; this.statusB3.ForeColor = Color.LimeGreen; this.statusB4.ForeColor = Color.LimeGreen; this.statusB5.ForeColor = Color.LimeGreen;
            this.statusB1.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.statusB2.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.statusB3.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.statusB4.Font = new Font("Segoe UI", 7F, FontStyle.Bold); this.statusB5.Font = new Font("Segoe UI", 7F, FontStyle.Bold);
            this.stationBStatus.Controls.AddRange(new Control[] { this.statusB1, this.statusB2, this.statusB3, this.statusB4, this.statusB5 });
            this.programLog.Dock = DockStyle.Fill;
            this.programLog.Multiline = true;
            this.programLog.ReadOnly = true;
            this.programLog.ScrollBars = ScrollBars.Vertical;
            this.programLog.BorderRadius = 4;
            this.programLog.BorderColor = Color.FromArgb(175, 188, 200);
            this.programLog.FillColor = Color.White;
            this.programLog.ForeColor = Color.Green;
            this.programLog.Font = new Font("Consolas", 7.3F);
            this.programLog.Text = "[2026/08/31 15:55:35:007] Initial Temperature Control Right DUT...\r\n[2026/08/31 15:55:35:114] Init TEC station B control Failure\r\n[2026/08/31 15:55:35:228] Set laser temperature Failure\r\n[2026/08/31 15:55:35:338] TEC Station B control not connected\r\n[2026/08/31 15:55:35:553] Initial Station A SSH Communication...\r\n[2026/08/31 15:55:35:658] System.Net.Sockets.SocketException\r\n  at Renci.SshNet.SocketAbstraction.ConnectCore()\r\n  at Renci.SshNet.Connection.ConnectorBase.SocketConnect()\r\n  at Renci.SshNet.Session.Connect()\r\n  at Octopus_Nova.FormNova.Initial_Device() line 1027\r\n[2026/08/31 15:55:38:658] Initial Station B SSH Communication...\r\n[2026/08/31 15:55:41:712] Initial DAQ...\r\n[2026/08/31 15:55:41:847] Initialize DAQ failed: device unavailable\r\n[2026/08/31 15:55:43:936] Initial Barcode Reader...\r\n[2026/08/31 15:55:43:998] Test Pin Failure\r\n[2026/08/31 15:55:44:030] Initial Keyence Laser Meter...\r\n[2026/08/31 15:55:44:078] Initial Laser Meter Failure\r\n[2026/08/31 15:55:44:108] Initial Vacuum Control... Finish\r\n[2026/08/31 15:58:02:123] System initialization ready\r\n[2026/08/31 16:33:16:943] [Start Process] get pd noise on A\r\n[2026/08/31 16:33:16:968] Record Noise, Station A, Gear: 256\r\n[2026/08/31 16:33:35:856] [End Process] Finish Successfully.\r\n[2026/08/31 16:34:01:115] Move stage to safe position\r\n[2026/08/31 16:34:02:281] Vision alignment completed\r\n[2026/08/31 16:34:03:440] Process waiting for next unit.";

            this.loadCellLayout.Dock = DockStyle.Fill;
            this.loadCellLayout.ColumnCount = 4;
            this.loadCellLayout.RowCount = 2;
            this.loadCellLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 27F));
            this.loadCellLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 27F));
            this.loadCellLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 27F));
            this.loadCellLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 19F));
            this.loadCellLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            this.loadCellLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            this.loadCell1.Text = "Load Cell: 000.000"; this.loadCell1.Dock = DockStyle.Fill; this.loadCell1.FillColor = Color.FromArgb(231, 231, 231); this.loadCell1.ForeColor = Color.FromArgb(48, 58, 66); this.loadCell1.BorderRadius = 3; this.loadCell1.Font = new Font("Segoe UI", 8F, FontStyle.Bold); this.loadCell1.Margin = new Padding(3);
            this.loadCell2.Text = "Load Cell: Disable."; this.loadCell2.Dock = DockStyle.Fill; this.loadCell2.FillColor = Color.FromArgb(231, 231, 231); this.loadCell2.ForeColor = Color.FromArgb(48, 58, 66); this.loadCell2.BorderRadius = 3; this.loadCell2.Font = new Font("Segoe UI", 8F, FontStyle.Bold); this.loadCell2.Margin = new Padding(3);
            this.loadCell3.Text = "Load Cell: 000.000"; this.loadCell3.Dock = DockStyle.Fill; this.loadCell3.FillColor = Color.FromArgb(231, 231, 231); this.loadCell3.ForeColor = Color.FromArgb(48, 58, 66); this.loadCell3.BorderRadius = 3; this.loadCell3.Font = new Font("Segoe UI", 8F, FontStyle.Bold); this.loadCell3.Margin = new Padding(3);
            this.loadCell4.Text = "Load Cell: 000.000"; this.loadCell4.Dock = DockStyle.Fill; this.loadCell4.FillColor = Color.FromArgb(231, 231, 231); this.loadCell4.ForeColor = Color.FromArgb(48, 58, 66); this.loadCell4.BorderRadius = 3; this.loadCell4.Font = new Font("Segoe UI", 8F, FontStyle.Bold); this.loadCell4.Margin = new Padding(3);
            this.emergencyStop.Text = "STOP";
            this.emergencyStop.Dock = DockStyle.Fill;
            this.emergencyStop.FillColor = Color.FromArgb(235, 15, 42);
            this.emergencyStop.ForeColor = Color.White;
            this.emergencyStop.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            this.emergencyStop.BorderRadius = 8;
            this.emergencyStop.Margin = new Padding(5);
            this.loadCellLayout.Controls.Add(this.loadCell1, 0, 0);
            this.loadCellLayout.Controls.Add(this.loadCell2, 1, 0);
            this.loadCellLayout.Controls.Add(this.loadCell3, 2, 0);
            this.loadCellLayout.Controls.Add(this.loadCell4, 0, 1);
            this.loadCellLayout.Controls.Add(this.emergencyStop, 3, 0);
            this.loadCellLayout.SetRowSpan(this.emergencyStop, 2);

            this.stationBLayout.Controls.Add(this.programLog, 0, 0);
            this.stationBLayout.Controls.Add(this.loadCellLayout, 0, 1);

            this.footerLabel.Text = "Copyright © 2024 Octopus Technology Ltd. All rights reserved";
            this.footerLabel.Dock = DockStyle.Fill;
            this.footerLabel.AutoSize = false;
            this.footerLabel.BackColor = Color.FromArgb(91, 164, 231);
            this.footerLabel.ForeColor = Color.FromArgb(28, 70, 107);
            this.footerLabel.TextAlignment = ContentAlignment.MiddleCenter;

            this.rootLayout.Controls.Add(this.headerLayout, 0, 0);
            this.rootLayout.Controls.Add(this.bodyLayout, 0, 1);
            this.rootLayout.Controls.Add(this.footerLabel, 0, 2);
            this.Controls.Add(this.rootLayout);
            this.borderlessForm.ContainerControl = this;
            this.borderlessForm.BorderRadius = 0;
            this.borderlessForm.ResizeForm = true;
            this.borderlessForm.TransparentWhileDrag = true;
            this.AutoScaleDimensions = new SizeF(96F, 96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.BackColor = Color.White;
            this.ClientSize = new Size(1586, 799);
            this.MinimumSize = new Size(1280, 720);
            this.Name = "UI";
            this.Text = "TopUs Nova AA-2 - Equipment Control";
            this.FormBorderStyle = FormBorderStyle.None;
            this.WindowState = FormWindowState.Maximized;
            this.ResumeLayout(false);
        }

    }
}
